package com.projectpulse.model.enums;

public enum ActivityCategory {
    DEVELOPMENT, TESTING, BUGFIX, COMMUNICATION, DOCUMENTATION,
    DESIGN, PLANNING, LEARNING, DEPLOYMENT, SUPPORT, MISCELLANEOUS
}
